apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth
  namespace: eats-lab
type: Opaque
stringData:
  username: eats
  password: eatslab
  # MassTransit / apps will use:
  # amqp://eats:eatslab@rabbitmq:5672/
  amqp-url: amqp://eats:eatslab@rabbitmq:5672/
