apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: eats-lab
  labels:
    app: order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - name: http
      port: 80
      targetPort: http
